local config = {
	HEALTH_CHECK_ENABLED = true,
	HEALTH_CHECK_INTERVAL = 10,
	HEALTH_CHECK_URL = "http://ioclient.dnsname.com:9191",
	HEALTH_CHECK_LIMIT = 1,
	HEALTH_CHECK_MODBUS_DEV = "192.168.7.2",
	HEALTH_CHECK_MODBUS_PORT = 502,
	HEALTH_CHECK_ERR_COIL = 106,
	HEALTH_CHECK_ERR_VAL = 0,
	SERVER_KEY = "123",
	SERVER_PORT = 9000,
	SERVER_HOST = "*",
	LOG_NAME = "IOSERVER",
	LOG_LEVEL = "INFO"
}

return config